### ISSUE TITLE
希望支持一下thinkphp 6

### ISSUE THREAD

**Issue by rjwu123** [zhangweiwei0326/api-doc#14]

**Comment by ruansuccess** [comment]
同上 希望尽快支持

**Comment by weixiaocheng** [comment]
非常流弊的框架, 希望支持thinkphp6

**Comment by misscx** [comment]
我改了一下，支持了TP6，可试一下。
`composer require misscx/api-doc
`
地址：
https://github.com/misscx/api-doc

**Comment by zhangweiwei0326** [comment]
已经支持了 访问doc/index
