### ISSUE TITLE
我使用的时候没有效果

### ISSUE THREAD

**Issue by Awayest** [zhangweiwei0326/api-doc#15]
显示找不到模块doc

**Comment by 1915210655** [comment]
我也是，我看了下源码，定义的路由是：doc/index， 使用 域名/doc/index 既可正常访问

**Comment by zhangweiwei0326** [comment]
> 我也是，我看了下源码，定义的路由是：doc/index， 使用 域名/doc/index 既可正常访问
这是标准答案
